import { Amiri } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "next-themes";

const amiri = Amiri({ 
  weight: ["400" , "700"],
  subsets: ["arabic"]
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (

    <html lang="ar">
      <body className={amiri.className}>
        <ThemeProvider attribute="class">
          {children}
        </ThemeProvider>
      </body>
    </html>

  );
}
